import type { Metadata } from "next";
//import { Inter } from "next/font/google"; usado para importar fonte
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Typesaude",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
